export enum DBConstants {
  REDIS_PASSWORD='REDIS_PASSWORD',
  REDIS_CONFIG='REDIS_CONFIG'
}

export enum AuthTypes {
  GOOGLE_AUTH='GOOGLE_AUTH',
  FACEBOOK_AUTH='FACEBOOK_AUTH',
  TWITTER_AUTH='TWITTER_AUTH',
  JWT_AUTH='JWT_AUTH'
}

export enum GoogleAuthConstants {
  GOOGLE_CLIENT_ID='GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET='GOOGLE_CLIENT_SECRET',
  GOOGLE_CALL_BACK_URL='GOOGLE_CALL_BACK_URL'
}

export enum FacebookAuthConstants {
  FACEBOOK_CLIENT_ID='FACEBOOK_CLIENT_ID',
  FACEBOOK_CLIENT_SECRET='FACEBOOK_CLIENT_SECRET',
  FACEBOOK_CALL_BACK_URL='FACEBOOK_CALL_BACK_URL',
  FACEBOOK_PROFILE_OPTIONS='FACEBOOK_PROFILE_OPTIONS'
}

export enum TwitterAuthConstants {
  TWITTER_CLIENT_ID='TWITTER_CLIENT_ID',
  TWITTER_CLIENT_SECRET='TWITTER_CLIENT_SECRET',
  TWITTER_CALL_BACK_URL='TWITTER_CALL_BACK_URL'
}

export enum JWTAuthConstants {
  JWT_ISSUER='JWT_ISSUER',
  JWT_AUDIENCE='JWT_AUDIENCE',
  JWT_ALGORITHMS='JWT_ALGORITHMS',
  JWT_SECRET='JWT_SECRET'
}

export enum ClientConstants {
  USER_SERVER='USER_SERVER',
  HTTP_CLIENT='HTTP_CLIENT',
  SAVE_USER_URL='SAVE_USER_URL'
}
